image:
  file: .gitpod.Dockerfile

tasks:
  # -------------------------------------------------
  # Install Cqlsh for Astra and setup for a DB
  # -------------------------------------------------
  - name: cassandra-astra
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      chmod 700 /workspace/conference-2022-devoxx/scripts/astra-cqlsh
      chmod 700 /workspace/conference-2022-devoxx/scripts/astra-cqlsh-install
      chmod 700 /workspace/conference-2022-devoxx/scripts/cassandra-start
      chmod 700 /workspace/conference-2022-devoxx/scripts/cassandra-cqlsh
    command: |
      ./scripts/astra-cqlsh-install
  - name: cassandra-docker
    before: |
      docker pull cassandra:4.0.3
    command: |
      ./scripts/cassandra-start 2>/dev/null
      ./scripts/cassandra-cqlsh
ports:
  # Access Cassandra node
  - port: 9042
    onOpen: ignore
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    # Lombok
    - GabrielBB.vscode-lombok
    # Java
    - vscjava.vscode-java-pack
    # Spring Boot
    - Pivotal.vscode-boot-dev-pack
    # Docker Containers
    - ms-azuretools.vscode-docker
  
