image:
  file: .gitpod.Dockerfile

tasks:
  - name: astra-cqlsh
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      chmod 700 /workspace/conference-2022-devoxx/astra-cqlsh
      chmod 700 /workspace/conference-2022-devoxx/astra-cqlsh-install
      chmod 700 /workspace/conference-2022-devoxx/cassandra-start
      chmod 700 /workspace/conference-2022-devoxx/cassandra-cqlsh
    command: |
      ./astra-cqlsh-install
  - name: local-cqlsh
    before: |
      docker pull cassandra:4.0.3
    command: |
      ./cassandra-start
ports:
  - port: 9042
    onOpen: ignore
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - GabrielBB.vscode-lombok
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
