image:
  file: .gitpod.Dockerfile

tasks:
  - name: lab4_cassandra_drivers
    before: |
      chmod 700 /workspace/conference-2022-devoxx/labs/lab4_cassandra/lab4_cassandra_drivers_init
    command: |
      ./labs/lab4_cassandra/lab4_cassandra_drivers_init
  - name: lab5_spring_data
    before: |
      chmod 700 /workspace/conference-2022-devoxx/labs/lab5_spring_data/lab5_spring_data_init
    command: |
      ./labs/lab5_spring_data/lab5_spring_data_init
  - name: lab6_quarkus
    before: |
      chmod 700 /workspace/conference-2022-devoxx/labs/lab6_quarkus/lab6_quarkus_init
    command: |
      ./labs/lab6_quarkus/lab6_quarkus_init
  - name: lab7_micronaut
    before: |
      chmod 700 /workspace/conference-2022-devoxx/labs/lab7_micronaut/lab7_micronaut_init
    command: |
      ./labs/lab7_micronaut/lab7_micronaut_init
  - name: gp
    command: |
      gp url 8080


  # -------------------------------------------------
  # Install Cqlsh for Astra and setup for a DB
  # -------------------------------------------------
  - name: cassandra-astra
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      chmod 700 /workspace/conference-2022-devoxx/labs/lab1_initialisation_environnements/astra-cqlsh
      chmod 700 /workspace/conference-2022-devoxx/labs/lab1_initialisation_environnements/astra-cqlsh-install
      chmod 700 /workspace/conference-2022-devoxx/labs/lab1_initialisation_environnements/cassandra-start
      chmod 700 /workspace/conference-2022-devoxx/labs/lab1_initialisation_environnements/cassandra-cqlsh
    command: |
      ./labs/lab1_initialisation_environnements/astra-cqlsh-install
  - name: cassandra-docker
    before: |
      docker pull cassandra:4.0.3
    command: |
      ./labs/lab1_initialisation_environnements/cassandra-start 2>/dev/null
  
ports:
  # Cassandra Node in Docker
  - port: 9042
    onOpen: ignore
    visibility: public
  # Spring Application
  - port: 8080
    onOpen: open-browser
    visibility: public
  # Quarkus Application
  - port: 8081
    onOpen: open-browser
    visibility: public 
  # Micronaut Application
  - port: 5005
    onOpen: ignore
    visibility: public      
  # Micronaut Application
  - port: 8082
    onOpen: open-browser
    visibility: public   

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    # Lombok
    - GabrielBB.vscode-lombok
    # Java
    - vscjava.vscode-java-pack
    # Spring Boot
    - Pivotal.vscode-boot-dev-pack
    # Docker Containers
    - ms-azuretools.vscode-docker
  
