image:
  file: .gitpod.Dockerfile

tasks:
  - name: astra-cqlsh
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      chmod 700 /workspace/conference-2022-devoxx/astra-cqlsh
      chmod 700 /workspace/conference-2022-devoxx/astra-cqlsh-install
    command: |
      ./astra-cqlsh-install
  - name: local-cqlsh
    before: |
      docker pull cassandra:4.0.3
    command: |
      clear
      echo "Starting Cassandra 4....."
      docker-compose -f /workspace/conference-2022-devoxx/hands-on/LAB_01/docker-compose-1noeud.yml
      echo "Ready"
ports:
  - port: 9042
    onOpen: open-browser
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - GabrielBB.vscode-lombok
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
