image:
  file: .gitpod.Dockerfile

tasks:
  - name: astra-cqlsh
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      chmod 700 /workspace/workshop-spring-reactive/install-cqlsh
      chmod 700 /workspace/workshop-spring-reactive/cqlsh
    command: |
      ./install-cqlsh
      ./cqlsh
   - name: LAB1
     before: |
       docker pull cassandra:4.0.3
     command: |
       clear
       echo "This is the Terminal for LAB1 with local Cassandra"
       docker images
ports:
  - port: 9042
    onOpen: open-browser
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - GabrielBB.vscode-lombok
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
