version: '2'

services:
  
  dc1n1: 
    image: cassandra:3.11.11
    networks:
      - backend
    ports:
      - 9052:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  dc1n2: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc1n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  dc1n3: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc1n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      
      
  dc2n1: 
    image: cassandra:3.11.11
    networks:
      - backend
    ports:
      - 9062:9042
    mem_limit: 2G
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1,dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  dc2n2:
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 30 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc2n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1,dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
  
  dc2n3: 
    image: cassandra:3.11.11
    command: /bin/bash -c "echo 'Waiting for seed node' && sleep 80 && /docker-entrypoint.sh cassandra -f"
    networks:
      - backend
    mem_limit: 2G
    depends_on:
      - dc2n1
    environment:
      - HEAP_NEWSIZE=128M
      - MAX_HEAP_SIZE=1024M
      - CASSANDRA_SEEDS=dc2n1,dc1n1
      - CASSANDRA_CLUSTER_NAME=stargatefull
      - CASSANDRA_DC=DC2
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      
  #Stargate Nodes DC1
  dc1s1: 
    image: stargateio/stargate-3_11:v1.0.41
    depends_on: 
      - dc1n1
    networks:
      - backend
    ports:
      - 9053:9042
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 8083:8090
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=stargatefull
      - CLUSTER_VERSION=3.11
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - ENABLE_AUTH=true
      - RACK_NAME=rack1
      - DATACENTER_NAME=DC1
      - SEED=dc1n1
      
  dc1s2: 
    image: stargateio/stargate-3_11:v1.0.41
    depends_on: 
      - dc1n1
    networks:
      - backend
    ports: 
      - 9054:9042
      - 9090:8080
      - 9091:8081
      - 9092:8082
      - 9093:8090
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=stargatefull
      - CLUSTER_VERSION=3.11
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - ENABLE_AUTH=true
      - RACK_NAME=rack1
      - DATACENTER_NAME=DC1
      - SEED=dc1n1
  
  #Stargate Nodes DC2    
  dc2s1: 
    image: stargateio/stargate-3_11:v1.0.41
    depends_on: 
      - dc2n1
    networks:
      - backend
    ports:
      - 9063:9042
      - 6060:8080
      - 6061:8081
      - 6062:8082
      - 6063:8090
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=stargatefull
      - CLUSTER_VERSION=3.11
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - ENABLE_AUTH=true
      - RACK_NAME=rack1
      - DATACENTER_NAME=DC2
      - SEED=dc2n1
      
  dc2s2: 
    image: stargateio/stargate-3_11:v1.0.41
    depends_on: 
      - dc2n1
    networks:
      - backend
    ports: 
      - 9064:9042
      - 7070:8080
      - 7071:8081
      - 7072:8082
      - 7073:8090
    mem_limit: 2G
    environment:
      - JAVA_OPTS="-Xmx2G"
      - CLUSTER_NAME=stargatefull
      - CLUSTER_VERSION=3.11
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - ENABLE_AUTH=true
      - RACK_NAME=rack1
      - DATACENTER_NAME=DC2
      - SEED=dc2n1   
   
networks:
  backend:
