#!/bin/bash

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

clear
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}--  Astra CQLSH [Installation]                           ---${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"
mkdir /workspace/conference-2022-devoxx/tools 2>/dev/null
echo -e "${GREEN}[OK]${NC} - Folder 'tool' has been created"
cd /workspace/conference-2022-devoxx/tools
echo -e "${GREEN}[OK]${NC} - Downloading Package....."
wget -q https://downloads.datastax.com/enterprise/cqlsh-astra.tar.gz >> install-cqlsh.log
tar xvzf cqlsh-astra.tar.gz  >> install-cqlsh.log
rm -f cqlsh-astra.tar.gz >> install-cqlsh.log
echo -e "${GREEN}[OK]${NC} - Package has been downloaded"
cd /workspace/conference-2022-devoxx
echo -e "${GREEN}[OK]${NC} - Installing Astra Setup...."
npm install --silent astra-setup 2>/dev/null
echo -e "${GREEN}[OK]${NC} - Astra Setup is ready"



