#!/bin/bash

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

cd /workspace/conference-2022-devoxx/labs/lab4_cassandra_drivers
mvn clean compile
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}- DRIVERS [OK]                                             -${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"

cd /workspace/conference-2022-devoxx/labs/lab5_spring_data
mvn clean compile
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}- SPRING DATA [OK]                                         -${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"

cd /workspace/conference-2022-devoxx/labs/lab6_quarkus
mvn clean compile
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}- QUARKUS [OK]                                             -${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"

cd /workspace/conference-2022-devoxx/labs/lab7_micronaut
mvn clean compile
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}- MICRONAUT [OK]                                           -${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"

echo -e ""
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}-- Pret pour Java                                        ---${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e ""

