#!/bin/bash

GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e ""
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e "${BLUE}-- Test Java                                             ---${NC}"
echo -e "${BLUE}------------------------------------------------------------${NC}"
echo -e ""

cd /workspace/conference-2022-devoxx/labs/1-cassandra-drivers
mvn clean compile